const resList = [
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "667571",
			name: "Popeyes",
			uuid: "5fdc0488-c767-4322-83f4-f761e622253f",
			city: "1",
			area: "Koramangala",
			totalRatingsString: "100+ ratings",
			cloudinaryImageId: "61f2bd5d86640a55419ffe358af97b03",
			cuisines: ["Snacks", "Burgers"],
			tags: [],
			costForTwo: 50000,
			costForTwoString: "₹500 FOR TWO",
			deliveryTime: 41,
			minDeliveryTime: 41,
			maxDeliveryTime: 41,
			slaString: "41 MINS",
			lastMileTravel: 1.100000023841858,
			slugs: {
				restaurant: "popeyes-80-feet-road-koramangala",
				city: "bangalore",
			},
			cityState: "1",
			address: "Site No 9, PID No 67-7-9, 7th Block, 80 feet Road, Koramangala",
			locality: "80 feet Road",
			parentId: 397044,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			ribbon: [
				{
					type: "PROMOTED",
				},
			],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 3100,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 3100,
				message: "",
				title: "Delivery Charge",
				amount: "3100",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "cid=6465393~p=1~eid=00000187-8076-b2e4-0f1f-5ab100b10117",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.1 kms",
			hasSurge: false,
			sla: {
				restaurantId: "667571",
				deliveryTime: 41,
				minDeliveryTime: 41,
				maxDeliveryTime: 41,
				lastMileTravel: 1.100000023841858,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: true,
			avgRating: "4.1",
			totalRatings: 100,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "229",
			name: "Meghana Foods",
			uuid: "4fdd19e2-5d0f-4bde-9c7f-dc3e8d36021f",
			city: "1",
			area: "Koramangala",
			totalRatingsString: "10000+ ratings",
			cloudinaryImageId: "xqwpuhgnsaf18te7zvtv",
			cuisines: [
				"Biryani",
				"Andhra",
				"South Indian",
				"North Indian",
				"Chinese",
				"Seafood",
			],
			tags: [],
			costForTwo: 50000,
			costForTwoString: "₹500 FOR TWO",
			deliveryTime: 42,
			minDeliveryTime: 42,
			maxDeliveryTime: 42,
			slaString: "42 MINS",
			lastMileTravel: 1.2999999523162842,
			slugs: {
				restaurant: "meghana-foods-5th-block-koramangala",
				city: "bangalore",
			},
			cityState: "1",
			address:
				"124, Near Jyothi Nivas College, 1st Cross, KHB Colony, Koramangala 5th Block, Bangalore",
			locality: "5th Block",
			parentId: 635,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 3100,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 3100,
				message: "",
				title: "Delivery Charge",
				amount: "3100",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.2 kms",
			hasSurge: false,
			sla: {
				restaurantId: "229",
				deliveryTime: 42,
				minDeliveryTime: 42,
				maxDeliveryTime: 42,
				lastMileTravel: 1.2999999523162842,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.3",
			totalRatings: 10000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "121603",
			name: "Kannur Food Point",
			uuid: "51983905-e698-4e31-b0d7-e376eca56320",
			city: "1",
			area: "Tavarekere",
			totalRatingsString: "10000+ ratings",
			cloudinaryImageId: "bmwn4n4bn6n1tcpc8x2h",
			cuisines: ["Kerala", "Chinese"],
			tags: [],
			costForTwo: 30000,
			costForTwoString: "₹300 FOR TWO",
			deliveryTime: 31,
			minDeliveryTime: 31,
			maxDeliveryTime: 31,
			slaString: "31 MINS",
			lastMileTravel: 3,
			slugs: {
				restaurant: "kannur-food-point-btm",
				city: "bangalore",
			},
			cityState: "1",
			address:
				"6/21,9TH CROSS ,1ST MAIN, VENKATESHWARA LAYOUT,SG PALYA, BENGALURU, - 560093",
			locality: "SG Palya",
			parentId: 20974,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off on all orders",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off on all orders",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off on all orders",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 3900,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 3900,
				message: "",
				title: "Delivery Charge",
				amount: "3900",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "3 kms",
			hasSurge: false,
			sla: {
				restaurantId: "121603",
				deliveryTime: 31,
				minDeliveryTime: 31,
				maxDeliveryTime: 31,
				lastMileTravel: 3,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "3.9",
			totalRatings: 10000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "66806",
			name: "Habibi Falafel",
			uuid: "903ef8a8-b84f-4a45-ba8b-7e16d96b870a",
			city: "1",
			area: "Koramangala",
			totalRatingsString: "5000+ ratings",
			cloudinaryImageId: "gmqqfm0lyoq5cjsadgff",
			cuisines: ["Middle Eastern", "Lebanese", "Mediterranean", "Arabian"],
			tags: [],
			costForTwo: 25000,
			costForTwoString: "₹250 FOR TWO",
			deliveryTime: 28,
			minDeliveryTime: 28,
			maxDeliveryTime: 28,
			slaString: "28 MINS",
			lastMileTravel: 1.600000023841858,
			slugs: {
				restaurant: "habibi-falafel-koramangala-1st-block-koramangala",
				city: "bangalore",
			},
			cityState: "1",
			address: "969, 1st Main Rd, S.T. Bed, 1st Block Koramangala, Bangalore",
			locality: "1st Block",
			parentId: 9929,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "Flat ₹125 off",
				shortDescriptionList: [
					{
						meta: "Flat ₹125 off on orders above ₹249",
						discountType: "Flat",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
						discountType: "Flat",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "₹125 OFF",
				shortDescriptionList: [
					{
						meta: "Use MATCHDEAL125",
						discountType: "Flat",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "Flat ₹125 off on orders above ₹249 | Use code MATCHDEAL125",
						discountType: "Flat",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			ribbon: [
				{
					type: "PROMOTED",
				},
			],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 3100,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 3100,
				message: "",
				title: "Delivery Charge",
				amount: "3100",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "cid=6485966~p=4~eid=00000187-8076-b2e4-0f1f-5ab200b10408",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.6 kms",
			hasSurge: false,
			sla: {
				restaurantId: "66806",
				deliveryTime: 28,
				minDeliveryTime: 28,
				maxDeliveryTime: 28,
				lastMileTravel: 1.600000023841858,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: true,
			avgRating: "4.4",
			totalRatings: 5000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "59593",
			name: "Al Daaz",
			uuid: "c189b92c-d842-4595-9a1f-ff85bd67bc2a",
			city: "1",
			area: "Hsr Layout",
			totalRatingsString: "10000+ ratings",
			cloudinaryImageId: "rxsvhvcdip9dbfdijzk9",
			cuisines: [
				"American",
				"Arabian",
				"Chinese",
				"Desserts",
				"Mughlai",
				"North Indian",
			],
			tags: [],
			costForTwo: 40000,
			costForTwoString: "₹400 FOR TWO",
			deliveryTime: 51,
			minDeliveryTime: 51,
			maxDeliveryTime: 51,
			slaString: "51 MINS",
			lastMileTravel: 4.5,
			slugs: {
				restaurant: "al-daaz-hsr-hsr",
				city: "bangalore",
			},
			cityState: "1",
			address: "#64 & 65, 27th Main Rd, 1st Sector HSR Layout - 560102",
			locality: "HSR",
			parentId: 21640,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 3900,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 3900,
				message: "",
				title: "Delivery Charge",
				amount: "3900",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "4.5 kms",
			hasSurge: false,
			sla: {
				restaurantId: "59593",
				deliveryTime: 51,
				minDeliveryTime: 51,
				maxDeliveryTime: 51,
				lastMileTravel: 4.5,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.4",
			totalRatings: 10000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "337335",
			name: "Kannur food kitchen",
			uuid: "c70b61bc-0f68-4e24-996b-749fbf295c35",
			city: "1",
			area: "BTM Layout",
			totalRatingsString: "10000+ ratings",
			cloudinaryImageId: "a27weqanhnszqiuzsoik",
			cuisines: ["Kerala", "Biryani", "Beverages"],
			tags: [],
			costForTwo: 20000,
			costForTwoString: "₹200 FOR TWO",
			deliveryTime: 36,
			minDeliveryTime: 36,
			maxDeliveryTime: 36,
			slaString: "36 MINS",
			lastMileTravel: 2.5,
			slugs: {
				restaurant: "kannur-food-kitchen-btm-btm",
				city: "bangalore",
			},
			cityState: "1",
			address:
				"kannur food point, Chocolate Factory Road, Tavarekere, Cashier Layout, 1st Stage, BTM Layout, thavrakharea, Karnataka, India",
			locality: "1st  Stage",
			parentId: 114756,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "50% off",
				shortDescriptionList: [
					{
						meta: "50% off on all orders",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
					{
						meta: "Free Fresh Lime Juice on orders above ₹499",
						discountType: "Freebie",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off on all orders",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
					{
						meta: "Free Fresh Lime Juice on orders above ₹499",
						discountType: "Freebie",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "50% OFF",
				shortDescriptionList: [
					{
						meta: "",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "50% off on all orders",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
					{
						meta: "Free Fresh Lime Juice on orders above ₹499",
						discountType: "Freebie",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 3100,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 3100,
				message: "",
				title: "Delivery Charge",
				amount: "3100",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "2.5 kms",
			hasSurge: false,
			sla: {
				restaurantId: "337335",
				deliveryTime: 36,
				minDeliveryTime: 36,
				maxDeliveryTime: 36,
				lastMileTravel: 2.5,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "3.8",
			totalRatings: 10000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "18466",
			name: "Helloo Delhi",
			uuid: "c11c1470-b782-4358-a3cf-01545eae343b",
			city: "1",
			area: "Koramangala",
			totalRatingsString: "10000+ ratings",
			cloudinaryImageId: "bccd3dwxixe4rim4koe1",
			cuisines: ["North Indian"],
			tags: [],
			costForTwo: 33600,
			costForTwoString: "₹336 FOR TWO",
			deliveryTime: 31,
			minDeliveryTime: 31,
			maxDeliveryTime: 31,
			slaString: "31 MINS",
			lastMileTravel: 1.2000000476837158,
			slugs: {
				restaurant: "helloo-delhi-koramangala-4th-block-koramangala",
				city: "bangalore",
			},
			cityState: "1",
			address: "#770, 80ft Road, Koramangla 4th Block, Bengaluru 560034",
			locality: "4th Block",
			parentId: 2330,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "20% off",
				shortDescriptionList: [
					{
						meta: "20% off | Use TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "20% off up to ₹50 | Use code TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "20% OFF",
				shortDescriptionList: [
					{
						meta: "Use TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "20% off up to ₹50 | Use code TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			ribbon: [
				{
					type: "PROMOTED",
				},
			],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 3100,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 3100,
				message: "",
				title: "Delivery Charge",
				amount: "3100",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "cid=6485973~p=7~eid=00000187-8076-b2e4-0f1f-5ab300b10779",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.2 kms",
			hasSurge: false,
			sla: {
				restaurantId: "18466",
				deliveryTime: 31,
				minDeliveryTime: 31,
				maxDeliveryTime: 31,
				lastMileTravel: 1.2000000476837158,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: true,
			avgRating: "4.3",
			totalRatings: 10000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "428",
			name: "Biryani Pot",
			uuid: "6db20a8b-dd85-4148-b750-107169f7f826",
			city: "1",
			area: "Btm Layout",
			totalRatingsString: "10000+ ratings",
			cloudinaryImageId: "mdipoyzfzsa7n7igskht",
			cuisines: ["North Indian", "Biryani"],
			tags: [],
			costForTwo: 50000,
			costForTwoString: "₹500 FOR TWO",
			deliveryTime: 33,
			minDeliveryTime: 33,
			maxDeliveryTime: 33,
			slaString: "33 MINS",
			lastMileTravel: 1.899999976158142,
			slugs: {
				restaurant: "biryani-pot-madiwala-junction-btm",
				city: "bangalore",
			},
			cityState: "1",
			address: "14th  Cross, 4th link Road Maruthi Nagar Madiwala Bangalore 68",
			locality: "Maruti Nagar",
			parentId: 21798,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "20% off",
				shortDescriptionList: [
					{
						meta: "20% off | Use TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "20% off up to ₹50 | Use code TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "20% OFF",
				shortDescriptionList: [
					{
						meta: "Use TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "20% off up to ₹50 | Use code TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 3100,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 3100,
				message: "",
				title: "Delivery Charge",
				amount: "3100",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.8 kms",
			hasSurge: false,
			sla: {
				restaurantId: "428",
				deliveryTime: 33,
				minDeliveryTime: 33,
				maxDeliveryTime: 33,
				lastMileTravel: 1.899999976158142,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "3.9",
			totalRatings: 10000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "56589",
			name: "Roti-Wala",
			uuid: "257a0889-b243-4252-b84a-6c9f1760d58f",
			city: "1",
			area: "BTM Layout",
			totalRatingsString: "10000+ ratings",
			cloudinaryImageId: "ptetuqkrhmpd8tiqiztg",
			cuisines: [
				"North Indian",
				"Home Food",
				"Thalis",
				"Chinese",
				"Punjabi",
				"South Indian",
				"Ice Cream",
			],
			tags: [],
			costForTwo: 20000,
			costForTwoString: "₹200 FOR TWO",
			deliveryTime: 45,
			minDeliveryTime: 45,
			maxDeliveryTime: 45,
			slaString: "45 MINS",
			lastMileTravel: 4,
			slugs: {
				restaurant: "roti-wala-lavelle-road-central-bangalore",
				city: "bangalore",
			},
			cityState: "1",
			address: "#239, 7TH Cross, Btm Stage 2. NS Palya, 560076",
			locality: "2nd Stage",
			parentId: 415860,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "20% off",
				shortDescriptionList: [
					{
						meta: "20% off | Use TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "20% off up to ₹50 | Use code TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "20% OFF",
				shortDescriptionList: [
					{
						meta: "Use TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "20% off up to ₹50 | Use code TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 3900,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 3900,
				message: "",
				title: "Delivery Charge",
				amount: "3900",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "4 kms",
			hasSurge: false,
			sla: {
				restaurantId: "56589",
				deliveryTime: 45,
				minDeliveryTime: 45,
				maxDeliveryTime: 45,
				lastMileTravel: 4,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.2",
			totalRatings: 10000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "306639",
			name: "The Coorg Food Co.",
			uuid: "318c2c99-1173-42a8-b56c-f655e3cc5ffd",
			city: "1",
			area: "Koramangala",
			totalRatingsString: "1000+ ratings",
			cloudinaryImageId: "ej90ytd5x7ffyl6ii7cn",
			cuisines: ["South Indian"],
			tags: [],
			costForTwo: 75000,
			costForTwoString: "₹750 FOR TWO",
			deliveryTime: 34,
			minDeliveryTime: 34,
			maxDeliveryTime: 34,
			slaString: "34 MINS",
			lastMileTravel: 0.800000011920929,
			slugs: {
				restaurant: "the-coorg-food-co.-koramangala-koramangala",
				city: "bangalore",
			},
			cityState: "1",
			address:
				"No 466, Ground floor shop, 17th G main, 6th block, 80 feet road, opp BMTC Bus Depot, Koramangala, Bangalore",
			locality: "6th Block",
			parentId: 207214,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			ribbon: [
				{
					type: "PROMOTED",
				},
			],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 3100,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 3100,
				message: "",
				title: "Delivery Charge",
				amount: "3100",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "cid=6407699~p=10~eid=00000187-8076-b2e4-0f1f-5ab400b10a7f",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "0.8 kms",
			hasSurge: false,
			sla: {
				restaurantId: "306639",
				deliveryTime: 34,
				minDeliveryTime: 34,
				maxDeliveryTime: 34,
				lastMileTravel: 0.800000011920929,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: true,
			avgRating: "4.2",
			totalRatings: 1000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "425",
			name: "Hotel Empire",
			uuid: "c0c37758-2e83-4429-aad6-eb94debb48f5",
			city: "1",
			area: "Koramangala",
			totalRatingsString: "10000+ ratings",
			cloudinaryImageId: "un4omn7rcunkmlw6vikr",
			cuisines: ["North Indian", "Kebabs", "Biryani"],
			tags: [],
			costForTwo: 45000,
			costForTwoString: "₹450 FOR TWO",
			deliveryTime: 47,
			minDeliveryTime: 47,
			maxDeliveryTime: 47,
			slaString: "47 MINS",
			lastMileTravel: 1.2999999523162842,
			slugs: {
				restaurant: "hotel-empire-5th-block-koramangala",
				city: "bangalore",
			},
			cityState: "1",
			address:
				"103, Industrial Area, 5th Block, Near Jyothi Nivas College, Koramangala 5th Block, Bangalore",
			locality: "Koramangala",
			parentId: 475,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "10% off",
				shortDescriptionList: [
					{
						meta: "10% off | Use TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "10% off up to ₹40 | Use code TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "10% OFF",
				shortDescriptionList: [
					{
						meta: "Use TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "10% off up to ₹40 | Use code TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 3100,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 3100,
				message: "",
				title: "Delivery Charge",
				amount: "3100",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.2 kms",
			hasSurge: false,
			sla: {
				restaurantId: "425",
				deliveryTime: 47,
				minDeliveryTime: 47,
				maxDeliveryTime: 47,
				lastMileTravel: 1.2999999523162842,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.0",
			totalRatings: 10000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "413824",
			name: "Al Taza",
			uuid: "c475d02b-ff01-46fd-9a4f-ccf25a658345",
			city: "1",
			area: "Koramangala",
			totalRatingsString: "1000+ ratings",
			cloudinaryImageId: "e0a2deada3fd2737b6e3924b731a66b3",
			cuisines: ["Arabian", "Lebanese", "Fast Food"],
			tags: [],
			costForTwo: 30000,
			costForTwoString: "₹300 FOR TWO",
			deliveryTime: 29,
			minDeliveryTime: 29,
			maxDeliveryTime: 29,
			slaString: "29 MINS",
			lastMileTravel: 1.2999999523162842,
			slugs: {
				restaurant: "al-taza-koramangala-koramangala",
				city: "bangalore",
			},
			cityState: "1",
			address:
				"No. 1026 Al Taza, Ground Floor, 80 Feet Road, 4th Block Koramangala, Bangalore - 560034",
			locality: "4th Block",
			parentId: 322432,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "10% off",
				shortDescriptionList: [
					{
						meta: "10% off | Use MATCHPARTY",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "10% off | Use code MATCHPARTY",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "10% OFF",
				shortDescriptionList: [
					{
						meta: "Use MATCHPARTY",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "10% off | Use code MATCHPARTY",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			ribbon: [
				{
					type: "PROMOTED",
				},
			],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 3100,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 3100,
				message: "",
				title: "Delivery Charge",
				amount: "3100",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "cid=6485901~p=13~eid=00000187-8076-b2e4-0f1f-5ab500b10d20",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.2 kms",
			hasSurge: false,
			sla: {
				restaurantId: "413824",
				deliveryTime: 29,
				minDeliveryTime: 29,
				maxDeliveryTime: 29,
				lastMileTravel: 1.2999999523162842,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: true,
			avgRating: "4.5",
			totalRatings: 1000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "5934",
			name: "Burger King",
			uuid: "ac56f2ac-71d3-4978-9513-b3aa68e25463",
			city: "1",
			area: "Koramangala",
			totalRatingsString: "10000+ ratings",
			cloudinaryImageId: "28fb13049b4e55297bb3f703cde63c35",
			cuisines: ["Burgers", "American"],
			tags: [],
			costForTwo: 35000,
			costForTwoString: "₹350 FOR TWO",
			deliveryTime: 45,
			minDeliveryTime: 45,
			maxDeliveryTime: 45,
			slaString: "45 MINS",
			lastMileTravel: 1.600000023841858,
			slugs: {
				restaurant: "burger-king-koramangala",
				city: "bangalore",
			},
			cityState: "1",
			address:
				"Unit No. 1, Davar Atrium, Corporation No. 118, Koramangala Industrial Area 7th Block, Bangalore 560095",
			locality: "7th Block",
			parentId: 166,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "60% off",
				shortDescriptionList: [
					{
						meta: "60% off | Use STEALDEAL",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "60% off up to ₹120 | Use code STEALDEAL",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "60% OFF",
				shortDescriptionList: [
					{
						meta: "Use STEALDEAL",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "60% off up to ₹120 | Use code STEALDEAL",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 3100,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 3100,
				message: "",
				title: "Delivery Charge",
				amount: "3100",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "1.6 kms",
			hasSurge: false,
			sla: {
				restaurantId: "5934",
				deliveryTime: 45,
				minDeliveryTime: 45,
				maxDeliveryTime: 45,
				lastMileTravel: 1.600000023841858,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.2",
			totalRatings: 10000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "219",
			name: "Anjappar",
			uuid: "6744769f-4c22-4399-8a1a-baf829b03f04",
			city: "1",
			area: "Koramangala",
			totalRatingsString: "10000+ ratings",
			cloudinaryImageId: "fa25f646f0f18e7b1d854e3e8b4a8f1b",
			cuisines: [
				"Chettinad",
				"Thalis",
				"Biryani",
				"Chinese",
				"Tandoor",
				"South Indian",
				"North Indian",
			],
			tags: [],
			costForTwo: 60000,
			costForTwoString: "₹600 FOR TWO",
			deliveryTime: 35,
			minDeliveryTime: 35,
			maxDeliveryTime: 35,
			slaString: "35 MINS",
			lastMileTravel: 0.6000000238418579,
			slugs: {
				restaurant: "anjappar-4th-b-block-koramangala",
				city: "bangalore",
			},
			cityState: "1",
			address:
				"4, 17th Main, Near BDA Complex, 100 Feet Road, 4th B Block,Koramangala",
			locality: "Connaught Place",
			parentId: 61,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "40% off",
				shortDescriptionList: [
					{
						meta: "40% off | Use TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "40% off up to ₹80 | Use code TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "40% OFF",
				shortDescriptionList: [
					{
						meta: "Use TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "40% off up to ₹80 | Use code TRYNEW",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			ribbon: [
				{
					type: "PROMOTED",
				},
			],
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 3100,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 3100,
				message: "",
				title: "Delivery Charge",
				amount: "3100",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "cid=6428032~p=16~eid=00000187-8076-b2e4-0f1f-5ab600b11014",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "0.6 kms",
			hasSurge: false,
			sla: {
				restaurantId: "219",
				deliveryTime: 35,
				minDeliveryTime: 35,
				maxDeliveryTime: 35,
				lastMileTravel: 0.6000000238418579,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: true,
			avgRating: "4.0",
			totalRatings: 10000,
			new: false,
		},
		subtype: "basic",
	},
	{
		type: "restaurant",
		data: {
			type: "F",
			id: "201224",
			name: "Asha tiffins",
			uuid: "e32381cf-6468-4c10-9bad-47fa08e898a8",
			city: "1",
			area: "HSR Layout",
			totalRatingsString: "10000+ ratings",
			cloudinaryImageId: "n15vckntsiboiod3gpco",
			cuisines: ["Indian", "South Indian", "Beverages"],
			tags: [],
			costForTwo: 20000,
			costForTwoString: "₹200 FOR TWO",
			deliveryTime: 41,
			minDeliveryTime: 41,
			maxDeliveryTime: 41,
			slaString: "41 MINS",
			lastMileTravel: 4,
			slugs: {
				restaurant: "asha-tiffins-hsr-hsr-2",
				city: "bangalore",
			},
			cityState: "1",
			address:
				"Asha Tiffins, 5th Main Road, Sector 7, HSR Layout, Bengaluru, Karnataka, India",
			locality: "7th Sector",
			parentId: 236243,
			unserviceable: false,
			veg: true,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: "30% off",
				shortDescriptionList: [
					{
						meta: "30% off | Use TRYNEW-XL",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "30% off upto ₹80 | Use TRYNEW-XL",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			aggregatedDiscountInfoV2: {
				header: "30% OFF",
				shortDescriptionList: [
					{
						meta: "Use TRYNEW-XL",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				descriptionList: [
					{
						meta: "30% off upto ₹80 | Use TRYNEW-XL",
						discountType: "Percentage",
						operationType: "RESTAURANT",
					},
				],
				subHeader: "",
				headerType: 0,
				superFreedel: "",
			},
			chain: [],
			feeDetails: {
				fees: [
					{
						name: "distance",
						fee: 3900,
						message: "",
					},
					{
						name: "time",
						fee: 0,
						message: "",
					},
					{
						name: "special",
						fee: 0,
						message: "",
					},
				],
				totalFees: 3900,
				message: "",
				title: "Delivery Charge",
				amount: "3900",
				icon: "",
			},
			availability: {
				opened: true,
				nextOpenMessage: "",
				nextCloseMessage: "",
			},
			longDistanceEnabled: 0,
			rainMode: "NONE",
			thirdPartyAddress: false,
			thirdPartyVendor: "",
			adTrackingID: "",
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: "4 kms",
			hasSurge: false,
			sla: {
				restaurantId: "201224",
				deliveryTime: 41,
				minDeliveryTime: 41,
				maxDeliveryTime: 41,
				lastMileTravel: 4,
				lastMileDistance: 0,
				serviceability: "SERVICEABLE",
				rainMode: "NONE",
				longDistance: "NOT_LONG_DISTANCE",
				preferentialService: false,
				iconType: "EMPTY",
			},
			promoted: false,
			avgRating: "4.4",
			totalRatings: 10000,
			new: false,
		},
		subtype: "basic",
	},
];

export default resList;
